In [26]:
import numpy as np
import pandas as pd

In [ ]:
df_2020 = pd.read_csv('41053_2020.csv')
df_2021 = pd.read_csv('41053_2021.csv')
df_2022 = pd.read_csv('41053_2022.csv')
df_2023 = pd.read_csv('41053_2023.csv')

/var/folders/j6/gnlkxfsx0mz7c1ngs9mbs16m0000gn/T/ipykernel_91913/3199213827.py:1: DtypeWarning: Columns (0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv('41053_2020.csv')
/var/folders/j6/gnlkxfsx0mz7c1ngs9mbs16m0000gn/T/ipykernel_91913/3199213827.py:2: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv('41053_2021.csv')
/var/folders/j6/gnlkxfsx0mz7c1ngs9mbs16m0000gn/T/ipykernel_91913/3199213827.py:3: DtypeWarning: Columns (0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv('41053_2022.csv')
/var/folders/j6/gnlkxfsx0mz7c1ngs9mbs16m0000gn/T/ipykernel_91913/3199213827.py:4: DtypeWarning: Columns (0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv('41053_2023.csv')

In [29]:
merged_data = pd.concat([df_2020, df_2021, df_2022, df_2023], ignore_index=True)

In [30]:
merged_data.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,...,PRES,ATMP,WTMP,DEWP,VIS,TIDE,WDI,R WSP,D GST,WSP
0,#yr,mo,dy,hr,mn,degT,m/s,m/s,m,sec,...,T hPa,degC,degC,degC,mi,ft,NaN,NaN,NaN,NaN
1,2020,1,1,0,0,69,5.5,7.1,1.3,14.3,...,1014.4,26.7,28.1,999,99,99,NaN,NaN,NaN,NaN
2,2020,1,1,0,10,64,4.5,5.5,99,99,...,1014.4,26.6,999,999,99,99,NaN,NaN,NaN,NaN
3,2020,1,1,0,20,63,4.7,5.8,99,99,...,1014.5,26.9,999,999,99,99,NaN,NaN,NaN,NaN
4,2020,1,1,0,30,72,5.1,6.4,99,99,...,1014.6,27,999,999,99,99,NaN,NaN,NaN,NaN

In [31]:
# Step 4: Export the merged data to a CSV file
output_path = '/Users/jdhzy/Desktop/data/merged_data.csv'
merged_data.to_csv(output_path, index=False)
print("File exported to:", output_path)

File exported to: /Users/jdhzy/Desktop/data/merged_data.csv